# Generated by Django 4.0.6 on 2022-09-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_section', models.CharField(max_length=20)),
                ('image_section', models.ImageField(null=True, upload_to='sections/')),
                ('description_section', models.TextField(max_length=225)),
            ],
        ),
    ]
