# Generated by Django 4.0.6 on 2022-09-29 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('description_product', models.TextField(max_length=225)),
                ('image_product', models.ImageField(upload_to='products/')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sections.sections')),
            ],
        ),
    ]
