# Generated by Django 4.0.6 on 2022-10-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prducts',
            name='image_product',
            field=models.ImageField(null=True, upload_to='products/'),
        ),
    ]
