# Generated by Django 3.1.3 on 2022-10-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_prducts_image_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prducts',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
