# Generated by Django 4.2.2 on 2023-06-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20221005_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prducts',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
